In [87]:
# This is for the COMP9417 Group Project
# The problem is the OTTO in the Kaggle
# Source: https://www.kaggle.com/c/otto-group-product-classification-challenge/overview
# RandomForest / conception / svm / knn / Naive Bayesian

In [88]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn.metrics import log_loss
from sklearn import metrics
from sklearn.svm import SVC

In [89]:
raw_train_data = pd.read_csv("D:\\train.csv")
raw_test_data = pd.read_csv("D:\\test.csv")

In [90]:
print(raw_train_data.shape)
print(raw_test_data.shape)

(61878, 95)
(144368, 94)


In [91]:
Train_data = raw_train_data.iloc[:, 1:95]
labels = set(Train_data.iloc[:,93:94].target)
Valid_x = np.array(raw_test_data.iloc[:, 1:94])
Total_x = np.array(Train_data.iloc[:,0:93])
Total_y = np.array(Train_data.iloc[:,93:94])

In [92]:
print(f"The current has the following label {labels}")
print(f"The shape the Total_X {Total_x.shape}")
print(f"The shape the Total_Y {Total_y.shape}")
print(f"The shape the Valid_X {Valid_x.shape}")
print(f"Check Nan in Total_X {set(np.isnan(Total_x).any(axis=1))}")
# print(f"Check Nan in Train_Y {np.isnan(Train_Y).any(axis=1)}")
print(f"Check Nan in Valid_X {set(np.isnan(Valid_x).any(axis=1))}")

The current has the following label {'Class_4', 'Class_3', 'Class_8', 'Class_7', 'Class_2', 'Class_9', 'Class_1', 'Class_6', 'Class_5'}
The shape the Total_X (61878, 93)
The shape the Total_Y (61878, 1)
The shape the Valid_X (144368, 93)
Check Nan in Total_X {False}
Check Nan in Valid_X {False}


In [93]:
np.random.seed(10)
Total_X,Total_Y = shuffle(Total_x,Total_y)

In [94]:
# In this part using the previous 50000 to do the training and the last data to do the test check the score
Train_X = Total_X[:50000]
Train_Y = Total_Y[:50000]
Test_X = Total_X[50000:]
Test_Y = Total_Y[50000:]
print(Train_X.shape)
print(Train_Y.shape)
print(Test_X.shape)
print(Test_Y.shape)

(50000, 93)
(50000, 1)
(11878, 93)
(11878, 1)


In [95]:
C_dict = dict()

In [96]:
# for C in [10**x for x in range(-4,2)]:
#     svc = OneVsRestClassifier(LinearSVC(C=C , random_state=0))
#     svc.fit(Train_X, Train_Y)
#     C_dict.update({C:svc.score(Train_X, Train_Y)})

In [97]:
# print(C_dict)

In [98]:
# Best C: 0.1
# Best Score: 0.75044
# 0.1: 0.75326
best_C = 0.1

In [103]:
Test_Y_num = list()
for item in Test_Y:
    Test_Y_num.append([int(item[-1][-1])-1])
# print(Train_Y_num)
Test_Y_num = np.array(Test_Y_num)
print(Test_Y_num)

[[1]
 [5]
 [4]
 ...
 [4]
 [5]
 [1]]


In [104]:
svc = SVC(C=2, random_state=0)
svc.fit(Train_X, Train_Y.ravel())
svm_pred = svc.predict(Test_X)

In [106]:
normal_svm_predict = metrics.classification_report(Test_Y,svm_pred)
print(normal_svm_predict)

ValueError: Mix of label input types (string and number)

In [ ]:
print(Test_X)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
svm_proba_pred = svc.predict_proba(Test_X)
log_loss_result = log_loss(Test_Y, svm_proba_pred)
print(log_loss_result)

AttributeError: predict_proba is not available when  probability=False