In [36]:
# This is for the COMP9417 Group Project
# The problem is the OTTO in the Kaggle
# Source: https://www.kaggle.com/c/otto-group-product-classification-challenge/overview
# RandomForest / conception / svm / knn / Naive Bayesian

In [37]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn.metrics import log_loss
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

In [38]:
raw_train_data = pd.read_csv("D:\\train.csv")
raw_test_data = pd.read_csv("D:\\test.csv")

In [39]:
print(raw_train_data.shape)
print(raw_test_data.shape)

(61878, 95)
(144368, 94)


In [40]:
Train_data = raw_train_data.iloc[:, 1:95]
labels = set(Train_data.iloc[:,93:94].target)
Valid_x = np.array(raw_test_data.iloc[:, 1:94])
Total_x = np.array(Train_data.iloc[:,0:93])
Total_y = np.array(Train_data.iloc[:,93:94])

In [41]:
print(f"The current has the following label {labels}")
print(f"The shape the Total_X {Total_x.shape}")
print(f"The shape the Total_Y {Total_y.shape}")
print(f"The shape the Valid_X {Valid_x.shape}")
print(f"Check Nan in Total_X {set(np.isnan(Total_x).any(axis=1))}")
# print(f"Check Nan in Train_Y {np.isnan(Train_Y).any(axis=1)}")
print(f"Check Nan in Valid_X {set(np.isnan(Valid_x).any(axis=1))}")

The current has the following label {'Class_6', 'Class_1', 'Class_7', 'Class_3', 'Class_9', 'Class_8', 'Class_2', 'Class_5', 'Class_4'}
The shape the Total_X (61878, 93)
The shape the Total_Y (61878, 1)
The shape the Valid_X (144368, 93)
Check Nan in Total_X {False}
Check Nan in Valid_X {False}


In [42]:
np.random.seed(10)
Total_X,Total_Y = shuffle(Total_x,Total_y)

In [43]:
# In this part using the previous 50000 to do the training and the last data to do the test check the score
Train_X = Total_X[:50000]
Train_Y = Total_Y[:50000]
Test_X = Total_X[50000:]
Test_Y = Total_Y[50000:]
print(Train_X.shape)
print(Train_Y.shape)
print(Test_X.shape)
print(Test_Y.shape)

(50000, 93)
(50000, 1)
(11878, 93)
(11878, 1)


In [44]:
C_dict = dict()

In [45]:
# for C in [10**x for x in range(-4,2)]:
#     svc = OneVsRestClassifier(LinearSVC(C=C , random_state=0))
#     svc.fit(Train_X, Train_Y)
#     C_dict.update({C:svc.score(Train_X, Train_Y)})

In [46]:
# print(C_dict)

In [47]:
# Best C: 0.1
# Best Score: 0.75044
# 0.1: 0.75326
best_C = 0.1

In [48]:
Test_Y_num = list()
for item in Test_Y:
    Test_Y_num.append([int(item[-1][-1])-1])
# print(Train_Y_num)
Test_Y_num = np.array(Test_Y_num)
print(Test_Y_num)

[[1]
 [5]
 [4]
 ...
 [4]
 [5]
 [1]]


In [49]:
svc = SVC(C=2, random_state=0)
svc.fit(Train_X, Train_Y.ravel())
svm_pred = svc.predict(Test_X)

In [50]:
normal_svm_predict = metrics.classification_report(Test_Y,svm_pred)
print(normal_svm_predict)

              precision    recall  f1-score   support

     Class_1       0.69      0.50      0.58       346
     Class_2       0.67      0.90      0.77      3070
     Class_3       0.59      0.35      0.44      1484
     Class_4       0.80      0.33      0.46       495
     Class_5       0.97      0.96      0.97       586
     Class_6       0.95      0.94      0.94      2730
     Class_7       0.78      0.62      0.69       554
     Class_8       0.89      0.93      0.91      1650
     Class_9       0.86      0.89      0.87       963

    accuracy                           0.80     11878
   macro avg       0.80      0.71      0.74     11878
weighted avg       0.80      0.80      0.78     11878



In [54]:
from sklearn.svm import LinearSVC

In [58]:
Ada_svc = AdaBoostClassifier(SVC(C=2, random_state=0),n_estimators=100,random_state=0,algorithm='SAMME')
Ada_svc.fit(Train_X, Train_Y.ravel())
svm_pred = Ada_svc.predict(Test_X)

In [59]:
print(metrics.classification_report(Test_Y,svm_pred))

              precision    recall  f1-score   support

     Class_1       0.43      0.43      0.43       346
     Class_2       0.63      0.81      0.71      3070
     Class_3       0.42      0.25      0.31      1484
     Class_4       0.48      0.29      0.36       495
     Class_5       0.89      0.94      0.92       586
     Class_6       0.91      0.90      0.91      2730
     Class_7       0.59      0.54      0.56       554
     Class_8       0.87      0.82      0.85      1650
     Class_9       0.79      0.82      0.80       963

    accuracy                           0.73     11878
   macro avg       0.67      0.64      0.65     11878
weighted avg       0.71      0.73      0.71     11878



In [ ]:
print(Test_X)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


AttributeError: predict_proba is not available when  probability=False